interface PdfLineItem {
  description: string;
  quantity: string;
  unit_price: string;
  amount: string;
}

interface PdfInvoice {
  number: string;
  clientName: string;
  clientEmail: string | null;
  issueDate: string;
  dueDate: string;
  currency: string;
  notes: string;
  lineItems: PdfLineItem[];
  totals: {
    subtotal: string;
    tax: string;
    discount: string;
    total: string;
  };
}

const escapePdfText = (value: string): string =>
  value
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/\r?\n/g, ' ');

export const createInvoicePdfBuffer = (invoice: PdfInvoice): Buffer => {
  const bodyLines = [
    'Otilor Invoice',
    `Invoice Number: ${invoice.number}`,
    `Bill To: ${invoice.clientName}${invoice.clientEmail ? ` (${invoice.clientEmail})` : ''}`,
    `Issue Date: ${invoice.issueDate}`,
    `Due Date: ${invoice.dueDate}`,
    '',
    'Line Items',
    ...invoice.lineItems.slice(0, 18).map(
      (item) =>
        `- ${item.description} | ${item.quantity} x ${invoice.currency} ${item.unit_price} = ${invoice.currency} ${item.amount}`,
    ),
    '',
    `Subtotal: ${invoice.currency} ${invoice.totals.subtotal}`,
    `Tax: ${invoice.currency} ${invoice.totals.tax}`,
    `Discount: ${invoice.currency} ${invoice.totals.discount}`,
    `Total: ${invoice.currency} ${invoice.totals.total}`,
    invoice.notes ? `Notes: ${invoice.notes}` : 'Notes: None',
    '',
    'Generated by Otilor',
  ];

  const stream = [
    'BT',
    '/F1 12 Tf',
    '40 770 Td',
    ...bodyLines.flatMap((line, index) =>
      index === 0
        ? [`(${escapePdfText(line)}) Tj`]
        : ['0 -18 Td', `(${escapePdfText(line)}) Tj`],
    ),
    'ET',
  ].join('\n');

  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${Buffer.byteLength(stream, 'utf8')} >> stream\n${stream}\nendstream\nendobj`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${object}\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';

  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`;
  }

  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
};
